version: '3'

vars:
  # styles
  tw_src: './static/css/src.css'
  tw_dst: './static/css/out.css'
  # build
  target: './bin/bookly.exe'
  mainfile: './main.go'
  # migrations
  migrations-dir: './script/migrations'

env:
  PORT: :8080

tasks:
  # building an app
  build:
    cmds:
      - go build -o {{.target}} {{.mainfile}}
    silent: true

  # running an app
  run:
    cmds:
      - go run {{.mainfile}}
    silent: true

  # create new migration
  new-mig:
    cmd: goose -dir {{.migrations-dir}} create {{.CLI_ARGS}} sql

  # compile styles with standalone tailwindcss
  tailwind:
    cmds:
      - tailwindcss -i {{.tw_src}} -o {{.tw_dst}}
    silent: true
