db:
  host: db.rjvqrigxtbwnnektmvdz.supabase.co
  name: postgres
  port: 5432
  user: postgres
  password: supabaseisthe1
  ssl: disable

app:
  port: :8080
  signing-key: dfpaijfopaidjfopaiejfiopwaefjweio
  db-log-level: 2 # error level
  h-log-level: "error"
